"use strict";
const tg=window.Telegram?.WebApp;
const state={bootstrap:null,catalog:null,platform:null,family:null,service:null,quote:null};
const $=(id)=>document.getElementById(id);
const initData=tg?.initData||"";
const money=(value)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(value)||0);
const escapeText=(value)=>String(value??"");

if(tg){tg.ready();tg.expand();tg.setHeaderColor("#0b1220");tg.setBackgroundColor("#08101d");}

async function api(path,options={}){
  const response=await fetch(path,{...options,headers:{"Content-Type":"application/json","X-Telegram-Init-Data":initData,...options.headers}});
  let body={};try{body=await response.json();}catch{}
  if(!response.ok)throw new Error(body.detail||"Não foi possível concluir. Tente novamente.");
  return body;
}
function show(id){document.querySelectorAll(".view").forEach(el=>el.classList.add("hidden"));$(id).classList.remove("hidden");setStep(id);window.scrollTo({top:0,behavior:"smooth"});}
function setStep(id){const order=["platforms","families","services","order"];const current=Math.max(0,order.indexOf(id));document.querySelectorAll(".step").forEach((el,i)=>{el.classList.toggle("active",i===current);el.classList.toggle("done",i<current);});}
function toast(message){const el=$("toast");el.textContent=message;el.classList.remove("hidden");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.add("hidden"),3500);}
function busy(button,on,label){button.disabled=on;if(!button.dataset.label)button.dataset.label=button.textContent;button.textContent=on?label:button.dataset.label;}
function button(className,label,sub,onClick){const el=document.createElement("button");el.type="button";el.className=className;const strong=document.createElement("strong");strong.textContent=label;const small=document.createElement("small");small.textContent=sub;el.append(strong,small);el.addEventListener("click",onClick);return el;}

function renderPlatforms(){const grid=$("platformGrid");grid.replaceChildren();state.bootstrap.platforms.forEach((item,index)=>{const el=button("platform-card"+(index<2?" featured":""),item.name,`${item.count} opções`,()=>loadPlatform(item.name));const dot=document.createElement("div");dot.className="network-dot";el.prepend(dot);grid.append(el);});}
async function loadPlatform(name){try{state.platform=name;state.catalog=await api(`/api/catalog?platform=${encodeURIComponent(name)}`);$("familyPlatform").textContent=name;const grid=$("familyGrid");grid.replaceChildren();state.catalog.families.forEach(family=>{const count=state.catalog.services.filter(s=>s.family===family).length;grid.append(button("family-card",family,`${count} opções`,()=>selectFamily(family)));});show("families");tg?.HapticFeedback?.selectionChanged();}catch(error){toast(error.message);}}
function selectFamily(family){state.family=family;$("serviceContext").textContent=`${state.platform} · ${family}`;$("serviceSearch").value="";renderServices();show("services");tg?.HapticFeedback?.selectionChanged();}
function renderServices(){const needle=$("serviceSearch").value.trim().toLocaleLowerCase("pt-BR");const items=state.catalog.services.filter(s=>s.family===state.family&&(!needle||`${s.name} ${s.description}`.toLocaleLowerCase("pt-BR").includes(needle)));const list=$("serviceList");list.replaceChildren();if(!items.length){const empty=document.createElement("p");empty.className="empty";empty.textContent="Nenhum serviço encontrado nesta busca.";list.append(empty);return;}items.forEach(item=>{const card=document.createElement("button");card.type="button";card.className="service-card";const top=document.createElement("div");top.className="service-card-top";const id=document.createElement("span");id.className="service-id";id.textContent=`#${item.id}`;const name=document.createElement("strong");name.textContent=item.name;top.append(id,name);const desc=document.createElement("p");desc.textContent=item.description;const bottom=document.createElement("div");bottom.className="service-card-bottom";const limits=document.createElement("span");limits.textContent=item.kind==="package"?"Pacote fechado":`Min. ${item.minimum.toLocaleString("pt-BR")} · Máx. ${item.maximum.toLocaleString("pt-BR")}`;const price=document.createElement("b");price.textContent=item.kind==="package"?money(item.retailRate):`${money(item.retailRate)} / mil`;bottom.append(limits,price);card.append(top,desc,bottom);card.addEventListener("click",()=>selectService(item));list.append(card);});}
function selectService(item){state.service=item;state.quote=null;$("selectedBadge").textContent=`#${item.id}`;$("selectedName").textContent=item.name;$("selectedDescription").textContent=item.description;$("selectedLimits").textContent=item.kind==="package"?"Pacote fechado":`De ${item.minimum.toLocaleString("pt-BR")} a ${item.maximum.toLocaleString("pt-BR")}`;$("selectedRate").textContent=item.kind==="package"?`${money(item.retailRate)} total`:`${money(item.retailRate)} por mil`;const custom=item.kind==="custom comments";const packageType=item.kind==="package";$("valueField").classList.toggle("hidden",packageType);$("answerField").classList.toggle("hidden",item.kind!=="poll");const old=$("value");const replacement=custom?document.createElement("textarea"):document.createElement("input");replacement.id="value";replacement.autocomplete="off";if(custom){replacement.maxLength=3500;replacement.placeholder="Um comentário por linha";$("valueLabel").textContent="Comentários";$("valueHint").textContent=`De ${item.minimum} a ${item.maximum} linhas`;}else{replacement.inputMode="numeric";replacement.placeholder=`Entre ${item.minimum.toLocaleString("pt-BR")} e ${item.maximum.toLocaleString("pt-BR")}`;$("valueLabel").textContent="Quantidade";$("valueHint").textContent=`Mínimo ${item.minimum.toLocaleString("pt-BR")} · máximo ${item.maximum.toLocaleString("pt-BR")}`;}old.replaceWith(replacement);replacement.addEventListener("input",updatePrice);$("target").value="";$("answer").value="";updatePrice();show("order");}
function quantity(){const item=state.service;if(!item)return 0;if(item.kind==="package")return 1000;if(item.kind==="custom comments")return $("value").value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).length;return Number.parseInt($("value").value,10)||0;}
function estimatedPrice(){const item=state.service;if(!item)return 0;if(item.kind==="package")return Math.ceil(Number(item.retailRate)*100)/100;return Math.ceil((Number(item.retailRate)*quantity()/1000)*100)/100;}
function updatePrice(){$("livePrice").textContent=money(estimatedPrice());}
async function review(event){event.preventDefault();const item=state.service;const q=quantity();if(!$("target").value.trim()){toast("Informe o link ou @usuário.");return;}if(item.kind!=="package"&&(q<item.minimum||q>item.maximum)){toast(`A quantidade precisa ficar entre ${item.minimum} e ${item.maximum}.`);return;}const reviewButton=$("reviewButton");busy(reviewButton,true,"Calculando...");try{state.quote=await api("/api/quote",{method:"POST",body:JSON.stringify({service_id:item.id,target:$("target").value,value:item.kind==="package"?null:$("value").value,answer:item.kind==="poll"?$("answer").value:null})});$("reviewService").textContent=item.name;$("reviewTarget").textContent=$("target").value;$("reviewPrice").textContent=state.quote.costLabel;const after=Number(state.quote.balance)-Number(state.quote.cost);$("reviewBalance").textContent=money(Math.max(0,after));const insufficient=after<0;$("reviewWarning").classList.toggle("hidden",!insufficient);$("reviewWarning").textContent=insufficient?"Seu saldo é insuficiente. Adicione saldo pelo bot antes de confirmar.":"";$("confirmButton").disabled=insufficient;$("reviewModal").classList.remove("hidden");tg?.HapticFeedback?.impactOccurred("light");}catch(error){toast(error.message);}finally{busy(reviewButton,false,"");}}
async function confirmOrder(){const button=$("confirmButton");busy(button,true,"Enviando...");try{const result=await api(`/api/orders/${state.quote.id}/confirm`,{method:"POST",body:"{}"});if(result.state==="SUBMITTED"){$("successText").textContent=`Pedido ${result.id} enviado com sucesso. Acompanhe o andamento em Meus pedidos no bot.`;}else if(result.state==="UNKNOWN"){$("successText").textContent=`Pedido ${result.id} recebido e em verificação. Não tente novamente; acompanhe pelo bot.`;}else{throw new Error(result.error||"O pedido não pôde ser enviado.");}$("balanceLabel").textContent=result.balanceLabel;$("reviewModal").classList.add("hidden");show("success");tg?.HapticFeedback?.notificationOccurred("success");}catch(error){toast(error.message);tg?.HapticFeedback?.notificationOccurred("error");}finally{busy(button,false,"");}}
function back(target){if(target==="platforms")show("platforms");else if(target==="families")show("families");else if(target==="services")show("services");}
async function boot(){try{state.bootstrap=await api("/api/bootstrap");$("balanceLabel").textContent=state.bootstrap.balanceLabel;$("welcomeText").textContent=`Olá, ${state.bootstrap.user.firstName}. Escolha a rede e encontre o serviço certo sem listas gigantes.`;$("catalogSummary").textContent=`${state.bootstrap.serviceCount} opções disponíveis`;$("openBotAuth").href=state.bootstrap.botUrl;renderPlatforms();$("loading").classList.add("hidden");$("app").classList.remove("hidden");}catch(error){$("loading").classList.add("hidden");$("authError").classList.remove("hidden");$("authError").querySelector("p").textContent=error.message;}}

$("serviceSearch").addEventListener("input",renderServices);$("orderForm").addEventListener("submit",review);$("confirmButton").addEventListener("click",confirmOrder);document.querySelectorAll("[data-close-modal]").forEach(el=>el.addEventListener("click",()=>$("reviewModal").classList.add("hidden")));document.querySelectorAll("[data-back]").forEach(el=>el.addEventListener("click",()=>back(el.dataset.back)));document.querySelectorAll(".step").forEach(el=>el.addEventListener("click",()=>{const target=el.dataset.step;if(target==="platforms"||target==="families"&&state.catalog||target==="services"&&state.family||target==="order"&&state.service)show(target);}));$("newOrder").addEventListener("click",()=>{state.catalog=state.platform=state.family=state.service=state.quote=null;show("platforms");});$("closeApp").addEventListener("click",()=>tg?.close());$("balanceButton").addEventListener("click",()=>{const url=`${state.bootstrap?.botUrl||"https://t.me/MaisPopularBot"}?start=deposit`;tg?.openTelegramLink?tg.openTelegramLink(url):location.assign(url);});
boot();
